readme: update from the slides from the presentation
osbuild/manifest-db pull request #56
Opened 2022-10-04 14:30 UTC by lavocatt

From https://lavocatt.github.io/manifest-db-slides/#1

2022-10-14 06:21 UTC, ochosi commented on README.md
> +Image definitions are the Way we describe an image and do exist for every image
```suggestion
Image definitions are the way we describe an image and there is one for every image
```

2022-10-14 06:21 UTC, ochosi commented on README.md
> +- We need to run OSBuild against every one of them
```suggestion
- We need to run OSBuild against each one of them
```

2022-10-14 06:21 UTC, ochosi commented on README.md
> +- Check the build is *correct*
```suggestion
- Check whether the build is *correct*
```

2022-10-14 06:23 UTC, ochosi commented on README.md
> +[2h10](https://gitlab.com/redhat/services/products/image-builder/ci/manifest-db/-/jobs/3119412435) to build a set of manifests on a machine
This link is bound to expire soon, no?

2022-10-17 10:01 UTC, lavocatt commented on README.md
> +[2h10](https://gitlab.com/redhat/services/products/image-builder/ci/manifest-db/-/jobs/3119412435) to build a set of manifests on a machine
I'm trying to find out what's the gitlab policy regarding the storage lifecycle. I don't find any data on the subject. There's only timeout related information for CI's artifacts.

2022-10-17 14:16 UTC, ochosi commented
I think the content from the presentation makes sense in the README. However, I would expect it to be structured more like a README.
So basically start with what the thing in the repo is and what it does before getting into the weeds of defining terms.
Finally, the - from my pov - most important bit about the update workflow is currently at the bottom.

Just a very quick and dirty suggestion for a structure:

1. Introduction/Summary of what manifest-db is and does
2. Update cycle of manifest-db
3. Which problem does manifest-db solve (and what did we do before)
4. Appendix: Terminology
4.1 Manifests
4.2 Image Info
...

2022-10-18 08:23 UTC, ochosi requested changes
See my comment about the structure of the README

2022-10-18 10:14 UTC, lavocatt commented
> See my comment about the structure of the README

Thanks for the comments! I think it's quite better now :smile:

2022-10-18 10:14 UTC, lavocatt commented on README.md
> +[2h10](https://gitlab.com/redhat/services/products/image-builder/ci/manifest-db/-/jobs/3119412435) to build a set of manifests on a machine
I removed it in the end.

2022-11-04 07:32 UTC, ochosi commented
@lavocatt Thanks for the work you put into this - it's so much better :heart: 

There's only one more thing I can offer, which is language improvement suggestions. Let me know if you want me to review the text from that angle and add suggestions to it. Otherwise it's good to go from where I stand!

2022-11-04 07:32 UTC, ochosi approved these changes

2022-11-04 07:32 UTC, merged

2022-11-04 09:01 UTC, lavocatt commented
> @lavocatt Thanks for the work you put into this - it's so much better heart
> 
> There's only one more thing I can offer, which is language improvement suggestions. Let me know if you want me to review the text from that angle and add suggestions to it. Otherwise it's good to go from where I stand!

Thanks Simon for taking the time to review! Yes I would love to see your suggestions.