tools/image-info: bad syntax on rhel8 python
osbuild/manifest-db pull request #77
Opened 2023-02-10 13:10 UTC by lavocatt

We can't use:

with (a() as b, c() as d):
    pass

On older versions of python.

2023-02-10 13:20 UTC, achilleas-k requested changes

2023-02-10 13:20 UTC, achilleas-k commented on tools/image-info
> +          with host.ServiceManager(monitor=monitor.NullMonitor(1)) as mgr:
The indentation here is wrong

2023-02-10 13:27 UTC, lavocatt commented on tools/image-info
> +          with host.ServiceManager(monitor=monitor.NullMonitor(1)) as mgr:
I need to add a pep8 checker somewhere! Thanks.

2023-02-10 15:55 UTC, lavocatt commented
On this PR https://github.com/osbuild/manifest-db/pull/78 I tested that when image-info is not changed on the PR the regression test immediately return. On this PR they should run because image-info was changed.

2023-02-14 08:38 UTC, lavocatt commented
PR https://github.com/osbuild/manifest-db/pull/77 contains this commit and produced the update https://github.com/osbuild/manifest-db/pull/80 so everything's tested.

2023-02-15 10:29 UTC, ondrejbudai approved these changes

2023-02-15 12:36 UTC, achilleas-k approved these changes

2023-02-15 12:36 UTC, merged