COMPOSER-1959: Add RHEL 8.9 & 9.3 runners
osbuild/manifest-db pull request #92
Opened 2023-05-05 08:21 UTC by atodorov

2023-05-05 08:31 UTC, jrusz requested changes
This needs a new osbuild SHA in `Schutzfile`

2023-06-07 08:30 UTC, lavocatt commented
I think you can rebase this one on top of main and it should work better.

2023-06-16 06:03 UTC, jrusz commented on Schutzfile
> +      },
```suggestion
      }
```
This should make it a valid json.

2023-06-19 14:53 UTC, jrusz approved these changes

2023-06-20 08:00 UTC, merged